# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
# Reference the file where the CSV is located
weather_csv_path = "../WeatherPy/output_data/city_weather.csv"

# Import the data into a Pandas DataFrame
weather_df = pd.read_csv(weather_csv_path)
weather_df.pop("Unnamed: 0")

# Display dataframe
weather_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,agogo,6.8000,-1.0819,69.44,97.0,99.0,3.69,GH,1.619307e+09
1,sao joao da barra,-21.6403,-41.0511,71.76,84.0,10.0,3.51,BR,1.619307e+09
2,dire dawa,9.5931,41.8661,70.18,70.0,37.0,11.21,ET,1.619307e+09
3,ushuaia,-54.8000,-68.3000,50.00,57.0,40.0,9.22,AR,1.619307e+09
4,abu samrah,35.3029,37.1841,71.19,38.0,66.0,3.44,SY,1.619307e+09
...,...,...,...,...,...,...,...,...,...
529,sabang,5.8933,95.3214,82.60,71.0,100.0,14.54,ID,1.619308e+09
530,gillette,44.2911,-105.5022,55.99,50.0,90.0,17.27,US,1.619308e+09
531,grindavik,63.8424,-22.4338,44.60,100.0,90.0,19.57,IS,1.619308e+09
532,tres arroyos,-38.3739,-60.2798,55.80,70.0,46.0,9.44,AR,1.619308e+09
533,san felipe,10.3399,-68.7425,72.54,94.0,88.0,5.08,VE,1.619308e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
# Configure gmaps
gmaps.configure(api_key=g_key)

In [5]:
# Store latitude and longitude in locations
locations = weather_df[["Lat", "Lng"]]

# Store humidity for weight of the heatmap
humidity = weather_df["Humidity"]

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=100, point_radius=3)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
# Filter dataframe for ideal conditions
hotel_df = weather_df[(weather_df["Max Temp"] < 80) & (weather_df["Max Temp"] > 70) & (weather_df["Wind Speed"] < 10) & (weather_df["Cloudiness"] == 0)]

# Display dataframe
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
25,barra do garcas,-15.8900,-52.2567,73.40,78.0,0.0,1.19,BR,1.619307e+09
38,olinda,-8.0089,-34.8553,78.80,69.0,0.0,6.91,BR,1.619307e+09
43,maceio,-9.6658,-35.7353,75.20,94.0,0.0,4.61,BR,1.619307e+09
265,buraydah,26.3260,43.9750,77.00,23.0,0.0,4.61,SA,1.619307e+09
391,esna,25.2934,32.5540,77.00,20.0,0.0,9.33,EG,1.619308e+09
396,nazca,-14.8333,-74.9500,70.36,66.0,0.0,6.17,PE,1.619308e+09
417,do gonbadan,30.3586,50.7981,71.60,28.0,0.0,2.98,IR,1.619308e+09
509,mailsi,29.8003,72.1758,76.33,22.0,0.0,6.40,PK,1.619308e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [8]:
# Create empty list to store hotel names
hotel_names = []

# Store latitude and longitude in series
hotel_lat = hotel_df["Lat"]
hotel_lat = hotel_lat.reset_index(drop=True)
hotel_lng = hotel_df["Lng"]
hotel_lng = hotel_lng.reset_index(drop=True)

# Loop through and store hotel name for each city
for x in range(0, 8):
    
    # Store latitude and longitude as string
    lat_lng = f'{hotel_lat[x]},{hotel_lng[x]}'
    
    # Store parameters for search
    target_coordinates = lat_lng,
    target_search = "hotel"
    target_radius = 5000
    target_type = "lodging"

    # set up a parameters dictionary
    params = {
        "location": target_coordinates,
        "keyword": target_search,
        "radius": target_radius,
        "type": target_type,
        "key": g_key,
    }

    # Build URL
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Run request and store in json
    response = requests.get(base_url, params)
    hotel_response = response.json()
    
    # Store name and append to hotel name list
    hotel = hotel_response["results"][0]["name"]
    hotel_names.append(hotel)

# Add new column to hotel dataframe
hotel_df["Hotel Name"] = hotel_names

# Display dataframe
hotel_df

<ipython-input-8-3b888b49c5eb>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["Hotel Name"] = hotel_names

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
25,barra do garcas,-15.8900,-52.2567,73.40,78.0,0.0,1.19,BR,1.619307e+09,Odara Araguaia
38,olinda,-8.0089,-34.8553,78.80,69.0,0.0,6.91,BR,1.619307e+09,Hotel 7 Colinas
43,maceio,-9.6658,-35.7353,75.20,94.0,0.0,4.61,BR,1.619307e+09,Meridiano Hotel
265,buraydah,26.3260,43.9750,77.00,23.0,0.0,4.61,SA,1.619307e+09,MÃ¶venpick Hotel Qassim
391,esna,25.2934,32.5540,77.00,20.0,0.0,9.33,EG,1.619308e+09,Orient Star Dahabyia Isna 05 Nights Each Sunday
396,nazca,-14.8333,-74.9500,70.36,66.0,0.0,6.17,PE,1.619308e+09,Hotel Nazca Lines
417,do gonbadan,30.3586,50.7981,71.60,28.0,0.0,2.98,IR,1.619308e+09,Ù…Ù‡Ù…Ø§Ù† Ø³Ø±Ø§ÛŒ Ù…Ø±ØµØ§Ø¯
509,mailsi,29.8003,72.1758,76.33,22.0,0.0,6.40,PK,1.619308e+09,Mehar Hotel

In [9]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [10]:
# Add marker layer ontop of heat map

# Create heat layer
hotel_layer = gmaps.marker_layer(locations, hover_text= hotel_info)

# Add layer
fig.add_layer(hotel_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))